### ISSUE TITLE
[ELE-527] High memory consumption when running edr.

### ISSUE THREAD

**Issue by RoiTabach** [elementary-data/dbt-data-reliability#296]
**Describe the problem**
Seems some of the users running edr are experiencing too high memory usage. Affecting their ability to run in CI / other dockers orchestration, but not so good anyway

**Describe the solution**
needs to be investigated first

**Additional context**
Happened in 2 users in support over the last two days:

Jake - see [https://elementary-community.slack.com/archives/C02CTC89LAX/p1678895828557069](https://elementary-community.slack.com/archives/C02CTC89LAX/p1678895828557069)

Oliver - see [https://elementary-community.slack.com/archives/C02CTC89LAX/p1678963756105439](https://elementary-community.slack.com/archives/C02CTC89LAX/p1678963756105439)

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-527](https://linear.app/elementary/issue/ELE-527/high-memory-consumption-when-running-edr)</sub>

**Comment by RoiTabach** [comment]
Pinpointed to 0.6.6 being the problem.

Diff link: [https://github.com/elementary-data/elementary/compare/v0.6.5...v0.6.6#diff-b4d66a14c2a0fbfa326dd6016822e1305795a48942e4993f93db359dafdb0130](https://github.com/elementary-data/elementary/compare/v0.6.5...v0.6.6#diff-b4d66a14c2a0fbfa326dd6016822e1305795a48942e4993f93db359dafdb0130)

**Comment by RoiTabach** [comment]
From Jake: 

```
I have 0.6.5 working now, hit an error with 0.6.7, 0.6.8 hit OOM. Trying 0.6.6 now - hopefully bisecting through versions will help your team identify the root cause

```

**Comment by RoiTabach** [comment]
Now Jake ran 0.6.0 and got OK memory wise

2 things we added between these versions:

* dimension anomalies enrichment in the test results
* adding samples

Both of these looks like they are suspects

**Comment by RoiTabach** [comment]
Jake now ran on 0.6 and still had mem spike:

> Running on v 0.6.latest of both dbt and python packages I'm still seeing the memory spike but the stdout is a little more helpful. The memory spike happens between these 2 logs, seemingly towards the end of `get_test_results`

```
2023-03-16 13:49:35 — INFO — Running dbt --log-format json run-operation get_test_results --args {"days_back": 7, "invocations_per_test": 720, "metrics_sample_limit": 5, "disable_passed_test_metrics": false} --project-dir /app/.venv/lib/python3.11/site-packages/elementary/monitor/dbt_project --profiles-dir /app


2023-03-16 14:02:43 — INFO — Running dbt --log-format json run-operation get_dbt_models_test_coverage --project-dir /app/.venv/lib/python3.11/site-packages/elementary/monitor/dbt_project --profiles-dir /app
```

**Comment by RoiTabach** [comment]
```

352 models, 1388 tests
```

```
root@a5f55bf69bae:/app# dbt --version
Core:
  - installed: 1.4.5
  - latest:    1.4.5 - Up to date!

Plugins:
  - snowflake: 1.4.1 - Up to date!
```

(Jake)

**Comment by RoiTabach** [comment]
He's on dbt 1.4.5 (from the logs) and I have asked for adapter version (also from the other user with mem issues in orchestration)

**Comment by RoiTabach** [comment]
We need dbt and adapter versions

**Comment by RoiTabach** [comment]
This is the last command Jake's pod ran before dying (at least he died doing what it loved - running Python) 

```
dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "metrics_sample_limit": 5, "disable_passed_test_metrics": false}} --project-dir /app/.venv/lib/python3.11/site-packages/elementary/monitor/dbt_project --profiles-dir /app
```

**Comment by RoiTabach** [comment]
This is the cmdline that jake ran `edr monitor send-report --google-service-account-path /path/to/gcp.json --gcs-bucket-name my-bucket-name --update-bucket-website true -p /app` 

This is his edr.log from the docker:

[jake_edr_log_OOM_production.log](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/92cddc37-1817-4711-88fe-1fbbc566e853/f4fbe301-9128-416b-88ba-e9b0e32ba7f4)

**Comment by RoiTabach** [comment]
Jake sent me some details. He started investigating mem usage after seeing some error message from `multiprocess.py` saying there's %d semaphores left - so he got to see a spike of memory up to 4GB. 

He's on Python 3.11

edr - 0.7.5

His profiles.yml: 

```
arbor:
  target: DEVELOPER

  outputs:
    PROD:
      type: snowflake
      account: OBFUSCATED.us-central1.gcp
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: ETL_PROD_ROLE
      database: ARBOR
      warehouse: ETL_WH
      schema: PUBLIC
      threads: 8
      client_session_keep_alive: False

    DEVELOPER:
      type: snowflake
      account: OBFUSCATED.us-central1.gcp
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: DEVELOPER_ROLE
      database: TEST
      warehouse: ANALYST_WH
      schema: PUBLIC
      threads: 16
      client_session_keep_alive: False

    CI:
      type: snowflake
      account: OBFUSCATED.us-central1.gcp
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: GITHUB_INFRA_ROLE
      database: TEST
      warehouse: ETL_WH
      schema: PUBLIC
      threads: 16
      client_session_keep_alive: False

elementary:
  outputs:
    default:
      type: snowflake
      account: OBFUSCATED.us-central1.gcp
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: ETL_PROD_ROLE
      database: METADATA
      warehouse: ETL_WH
      schema: ELEMENTARY
      threads: 8
      client_session_keep_alive: False
```

He started running the production Docker locally with a 2GB mem limit to see it reproduce and he got it killed on OOM.

He ran the same docker locally without mem limit, got spikes of `up to 4.6gi memory at times`
