### ISSUE TITLE
Test failing to run since upgrading to 0.13

### ISSUE THREAD

**Issue by philk1991** [elementary-data/dbt-data-reliability#636]
Hey,

We're seeing a couple of tests failing to run since upgrading from 0.11.2 to 0.13. The tests in question have to use the `.` notation to look at the volume anomalies but this has been failing since the upgrade - FYI we're using databricks as our destination in dbt.

The test is displayed below.

```
      - name: transcription_jobs
        tests:
        - elementary.volume_anomalies:
            timestamp_column: updated_at.member0
            backfill_days: 1
            config:
              severity: warn
        - dbt_expectations.expect_table_row_count_to_be_between:
            min_value: 400000
```
I've also tried wrapping the timestamp column like this = timestamp_column: `updated_at.member0`. When doing this I receive a unicode error, which may or may not be related to this recent [change](https://github.com/elementary-data/elementary/pull/1312) on the python version of elementary.
